# Generated by Django 3.0.7 on 2020-06-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_title', models.CharField(max_length=200)),
                ('Director', models.CharField(max_length=200)),
                ('Starring', models.CharField(max_length=200)),
                ('Production_company', models.CharField(max_length=200)),
                ('Release_Date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
