# Generated by Django 3.0.7 on 2020-06-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200608_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Language',
            new_name='Langu',
        ),
    ]
