# Generated by Django 3.0.7 on 2020-06-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200608_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Langu',
        ),
    ]
