# Generated by Django 3.0.7 on 2020-06-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_movie_langu'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Movie_Language',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
    ]
