# Generated by Django 3.0.7 on 2020-06-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_movie_movie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='photos/'),
        ),
    ]
