# Generated by Django 3.0.7 on 2020-06-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200609_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Image2',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='photos/'),
        ),
    ]
