# Generated by Django 3.0.7 on 2020-06-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200610_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Image3',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Image4',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='photos/'),
        ),
    ]
