# Generated by Django 3.0.7 on 2020-06-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200610_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.CharField(default='DEFAULT VALUE', max_length=60),
        ),
    ]
